apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb-terra:8086
    jsonData:
      version: Flux
      organization: pearl-factory
      defaultBucket: sensor
    secureJsonData:
      token: my-influxdb-token
