{
 "title": "Overview3",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Real time Message Flow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 10s, fn: count, createEmpty: true)\r\n  |> yield(name: \"messages_per_10s\")"
    }
   ]
  },
  {
   "title": "활성 센서",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -1m)\r\n  |> group()\r\n  |> distinct(column: \"sensor_id\")\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Sensor Health Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> group(columns: [\"sensor_type\", \"sensor_id\"])\r\n  |> last()\r\n  |> group(columns: [\"sensor_type\"])\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Average Pressure",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.sensor_type == \"pressure\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> group()\r\n  |> mean()"
    }
   ]
  },
  {
   "title": "Average Production",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "litreh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.sensor_type == \"production\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> group()\r\n  |> mean()"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.sensor_type == \"temperature\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> group()\r\n  |> mean()"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.sensor_type == \"vibration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> group()\r\n  |> mean()"
    }
   ]
  },
  {
   "title": "Average Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r.sensor_type == \"humidity\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> group()\r\n  |> mean()"
    }
   ]
  }
 ]
}